CREATE TABLE IF NOT EXISTS urls (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(2048) NOT NULL UNIQUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS url_checks (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_id          BIGINT NOT NULL,
    status_code     INT NOT NULL,
    h1              VARCHAR(2048),
    title           VARCHAR(2048),
    description     TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (url_id) REFERENCES urls(id)
);
